time:
  start: "2024-01-01 00:00"
  steps: 6
  dt_min: 15

algorithm: OUR

admm:
  rho: 1.0
  max_iters: 100
  tol_primal: 1.0e-6
  tol_dual: 1.0e-6

solvers:
  tso: gurobi
  tso_options:
    max_iter: 300
  dso: gurobi
  time_limit_seconds: 5

tso:
  admittance:
    - [ 1.0, -1.0,  0.0]
    - [-1.0,  2.0, -1.0]
    - [ 0.0, -1.0,  1.0]
  injections: [-40.0, 10.0, 30.0]
  boundary: [2]
  cost_coeff: 10.0

dsos:
  - sens:
      Rp: [[0.01, 0.0], [0.0, 0.01]]
      Rq: [[0.0, 0.0], [0.0, 0.0]]
      vm_base: [1.0, 1.0]
    profiles:
      csv: data/profiles.csv
    vmin: 0.95
    vmax: 1.05
    penalty_voltage: 1000.0
    cost_coeff: 50.0

envelope:
  margin: 0.05
  alpha: 0.3

run:
  base: runs
  tag: demo

mapping:
  "2": [0, 0]

# Plot/output controls to avoid too many images
plots:
  admm_per_step:
    enabled: true
    latest_only: true   # overwrite a single latest image to prevent clutter
    stride: 0           # if >0 and latest_only=false, save every k steps
    dir: "admm"         # optional subdirectory for step plots
